### ISSUE TITLE
Evaluer utilisation de Strapi pour la gestion des contenus

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/common#10]
- [ ] test
- [ ] prise de RDV avec les commerciaux
- [ ] demande de devis (font-ils la prestation de service?)

**Comment by lenaMK** [comment]
@emchateau voudrais-tu toujours qu'on évalue Strapi?

**Comment by emchateau** [comment]
Oui, je pense que nous devons essayer. 
Je pense que je vais mettre en place une instance pour le site provisoire du projet. Cela me permettra sans doute de me faire une meilleure idée.
Amicalement,

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by emchateau** [comment]
Essais réalisés en local. Peu concluants. 
L’interface est pauvre et peu confortable. Le mode headless reproduit une séparation entre le backend dt le frontend qui n’est pas judicieuse. La gestion des types ne permet pas réellement de personnalisation de l’API.

Avantages
- internationalisation
- Api responsive pour les images 
- Création automatique des points d’accès 

j’ai évalué d’autres projets équivalents qui ne présentaient pas d’interface graphique pour la gestion des types qui pourraient être également intéressants. Ceux-ci utilisent des schémas JSON.

Je m’interroge vraiment sur la valeur ajoutée de pouvoir disposer d’une interface visuelle pour modifier les types dans notre contexte. Des lors, pourquoi utiliser une base sql et pas couchdb ou autre ?
