### ISSUE TITLE
Évaluer Islandora

### ISSUE THREAD

**Issue by emchateau** [ouvroir/common#11]
Islandora est une solution de partage de documents basée sur Drupal et Fedora https://islandora.ca/

**Comment by lenaMK** [comment]
@emchateau si tu as le temps de temps de regarder mes notes sur les différents outils évalués jusqu'à présent (dans le journal), ainsi que mes questions sur le scénario expots (dans scenari.md) avant notre rencontre demain ça pourrait être utile

**Comment by emchateau** [comment]
Entendu, merci beaucoup.
