### ISSUE TITLE
Lancer une conversation actualisée sur l'autohébergement et le système de fichier sur Zotero

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/common#14]
La documentation est assez sommaire sur Github. Existe

https://forums.zotero.org/discussion/73721/zotero-self-hosted
https://forums.zotero.org/discussion/comment/309275
https://forums.zotero.org/discussion/comment/316306

https://github.com/zotero/dataserver
https://github.com/mrtcode/zotero-server
https://github.com/gfacciol/zotero_dataserver-docker

- [x] se familiariser avec la documentation et les discussions pré-existantes
- [ ] identifier les lacunes / besoins actuels
- [ ] rédiger une question et la publier sur le forum Zotero

**Comment by lenaMK** [comment]
@emchateau j'ai rassemblé mes notes sur Zotero self-hosted dans [zotero.md](https://github.com/ouvroir/common/blob/main/zotero.md) . Je vais continuer à y mettre d'autres infos qui me semblent importante (genre les détails du fonctionnement/choix de webdav). Je suis aussi en train d'annoter l'[entrée de blogue à propos de Zotero6](https://www.zotero.org/blog/zotero-6/) sur l'hypothesis de l'Ouvroir pour me familiariser avec les nouvelles fonctionnalités etc.

**Comment by lenaMK** [comment]
1ère contribution au forum: erreur dans les liens https://forums.zotero.org/discussion/95618/small-bugreport-modify-path-for-links-in-advanced-preferences-documentation#latest

**Comment by lenaMK** [comment]
@emchateau 

De ce que j'ai compris de mes recherches, l'équipe de dev chez Zotero n'a aucunement le temps ni l'intention de travailler sur les options d'autohébergemet. Ça fait plusieurs années de suite que les gens posent la question sur le forum, avec tout le temps cette même réponse que ce n'est pas leur priorité (et on est quand même bien content·e·s de la nouvelle API) et surtout, que leur système est mal adapté pour êttre "packagé" pour l'autohébergement. 
Ma conclusion, c'est que l'auto-hébergement de Zotero n'est pas une piste viable pour nous

**Comment by emchateau** [comment]
C’est ce que m’avait dit Marcello de ses propres investigations il y a quelques années.
Dont acte !
