### ISSUE TITLE
IIIF - Test cantaloupe + metadonnées

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/common#24]
Trouver comment ajouter un lien vers les métadonnées de l’image lors de l’ajout d’une ressource dans un serveur IIIF?

- formats d’image,
- renommer l’image ?
- différents paramètres de traitement ? (images pyramidales jpeg2000)
- dépôt d’images en batch ?
- utilisation du filesystem ?

**Comment by lenaMK** [comment]
quelle est la pérénitté d'un lien produit par un serveur IIIF? Si je compare avec l'exemple des bibliothèque, le lien change à chaque fois qu'on déplace l'image. Il faudrait donc s'assurer que les images ne puissent pas être déplacées ou avoir une alternative de lien pérenne si possible

**Comment by lenaMK** [comment]
qui se charge de l'API de dépôt de données? 
→ requiert un accès au filesystem de cantaloupe

API doit aussi gérer l'intégration des métadonnées dans le fichier avec la solution 1
→ requiert au minimum le lien avec id Common

serveur public / serveur privé? distinguer/sécuriser les images servies pour common de celles pour l'encyclopédie
[delegate](https://cantaloupe-project.github.io/manual/5.0/access-control.html) (middleware) et ranger `par dossier` avec des instructions spéciales. couche authentification: système de session

XMP metadata: RDF, exemples dans [doc](https://cantaloupe-project.github.io/manual/5.0/metadata.html) cantaloupe avec dublinCore

**Comment by lenaMK** [comment]
avantages cantaloupe (au-delà du filesystem):
- gestion des formats des fichiers images
- imageAPI (dont définir des zones, formats...)

**Comment by lenaMK** [comment]
À discuter

- webservice pour dépot d'images 
- emplacement des métadonnées: entièrement sur common? 
- lien vers les métadonnées dans common dans l'image? ou seulement de common vers l'image? 

utilisation d'un manifeste pour publier des images avec les métadonnées: semble plus une question pour l'encyclopédie
