### ISSUE TITLE
Proposition intégration Kerko

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/common#35]
En ce qui concerne l'interaction avec l'API de Zotero, est-ce que ce ne serait pas intéressant de proposer l'intégration d'un service comme [Kerko](https://github.com/whiskyechobravo/kerko#how-it-works) qui permettrait aussi de rechercher dans l'ensemble des références bibliographiques rassemblées par CIECO? 

Marcello et Roch viennent de me parler de cet outil, ils veulent travailler à mettre en place un partanariat avec la BLSH et le CRN pour la perennisation des données de recherches (qui seraient stockées sur les serveurs de la bibli).

**Comment by emchateau** [comment]
Pour moi c’est ajouter un pile technologique. Je crains que cela ne complique l’affaire. Mais à suivre
