### ISSUE TITLE
Rédiger des scenari d’utilisation

### ISSUE THREAD

**Issue by emchateau** [ouvroir/common#7]
Afin de faciliter l’analyse des besoins et la rendre plus concrète il est utile de créer des cas d’utilisation qui pourront être soumis aux chercheuses et augmentés à partir des discussions qui interviendront avec elles.

**Comment by WilliamDiakite** [comment]
nettoyage des issues

**Comment by WilliamDiakite** [comment]
> 

Salut Emmanuel,

Lena et moi faisons un nettoyage des issues pour pouvoir réaliser un mini-sprint sur Common. Nous allons réouvrir des milestones et des issues plus précises (celles que nous enlevons ne sont pas assez atomiques).

**Comment by lenaMK** [comment]
@emchateau je peux fermer ce issue finalement?

**Comment by lenaMK** [comment]
c'est fait
