### ISSUE TITLE
Organiser des rencontres avec les chercheur·se·s

### ISSUE THREAD

**Issue by emchateau** [ouvroir/common#8]
Les rencontres avec les chercheur·se·s permettent de collecter et valider des cas d’utilisation.

**Comment by lenaMK** [comment]
@emchateau je suis en train de préparer la rencontre pour lundi. J'ai créé un [document pour la séance](https://github.com/ouvroir/common/blob/main/presentationCommon2022-01-31.md) et j'ai pensé que je pourrais notamment faire une sorte de sondage: à chaque fonctionnalité que je présente, chaque personne peut dire l'importance qui y est accordée (de 1 à 5), et ainsi on récupère facilement leur opinion sans avoir besoin d'un tour de table à chaque point. Les interventions concerneraient plutôt les précisions et questions ou les fonctionnalités jugées importantes. 
Je pourrais préparer une liste de fonctionnalités à présenter et faire un LimeSurvey par exemple, qu'en penses-tu?

**Comment by emchateau** [comment]
Salut Lena,

Cela me paraît une très bonne idée. En ajoutant toujours une question ouverte.
Comme la réunion sera sur Zoom, on pourrait faire un sondage dans Zoom.
Pour LimeSurvey, nous avons un service à l’Université https://sondages.umontreal.ca/sondages-en-ligne/ <https://sondages.umontreal.ca/sondages-en-ligne/>
Tu peux je pense te baser sur la liste de fonctionnalités que l’on avait déjà identifiée. 

Par contre, je pense qu’on aurait intérêt à conserver un début de réunion le plus ouvert possible pour obtenir des choses auxquelles on n’aurait pas vraiment pensé.
Peut être avec une technique d’animation sur demandant de décrire en une phrase courte à quoi servirait l’outil, etc.

Amitiés,

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by emchateau** [comment]
En fait, je pense que fonctionné par grand bloc de fonctionnalité après une première discussion générale peut être une bonne manière de scander la réunion. Cela apportera des respirations et peu amener les gens à réfléchir à la question.
Je crains un peu qu’avec la solution LimeSurvey, ils ne partent dans le tunnel de toutes les questions.
Les fonctionnalités de sondage sont assez limitées mais tu peux les préparer à l’avance dans une réunion.

Attention dans les questions à ne pas trop aller sur la question technique, mais de bien énoncer les choses en termes de fonctionnalités (utilisateur).

Amitiés,

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
Oui j'hésitais pour ce point, je vais préparer les sondages Zoom en ce cas (une fois qu'on aura arrêté notre choix sur l'ordre dans lequel présenter les fonctionnalités)

J'ai pensé qu'une présentation serait utile pour illustrer chaque fonctionnalité (ex: des vues d'espaces de travail). Je fais des petits tests graphique aussi, si tu veux jouer avec sur [canva](https://www.canva.com/design/DAE2qCY5d6g/share/preview?token=gfDKulbTwmV4Qn7BF5KYcA&role=EDITOR&utm_content=DAE2qCY5d6g&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by emchateau** [comment]
Salut,
Cela a du pep’s et c’est très élégant !
Tu pourrais ajouter une ligne de base genre « Ouvroir d’histoire de l’art et de muséologie numérique » sous le logo de la couverture.
Il faudrait sans doute également mettre en avant CIÉCO. Tu trouveras le logo dans le Drive.
N’hésites pas à varier les graisse si la police le permet pour les intertitre avec des semi-bold
Je reste assez convaincu que le Extra-Bold était mieux pour le logo et peut être pour les couvertures.
Amitiés,

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
Bons points merci, c'est ajouté (logo CIECO, ligne sur le labo: ouvroir ou laboratoire?)

J'ai un premier jet de structure (une page par fonctionnalité environ), j'ai mis quelques questions en commentaires, pourrais-tu aller voir ça quand tu as un moment stp? Je serai vraiment preneuse si tu as d'autres idées et suggestions! 

Merci et à demain!

**Comment by emchateau** [comment]
Désolé pour mes réponses tardives, j’avais du retard sur mes courriels.

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
Salut @emchateau , j'ai fait un premier retour sur les points soulevés pendant la rencontre dans le `journal.md`. Si tu as un moment pour le lire et évenutellement d'y ajouter tes commentaires et observations, je pourrais ensuite m'essayer à identifier la solution ciblée et commencer un cahier des charges.
